/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects/CalendarTabSimplified` | `/projects/CalendarTabSimplified`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects/PartTab` | `/projects/PartTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects/VenueTab` | `/projects/VenueTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects/[id]` | `/projects/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/projects/venue/[id]` | `/projects/venue/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projects/CalendarTabSimplified` | `/projects/CalendarTabSimplified`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projects/PartTab` | `/projects/PartTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projects/VenueTab` | `/projects/VenueTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projects` | `/projects`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projects/[id]` | `/projects/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/projects/venue/[id]` | `/projects/venue/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projects/CalendarTabSimplified${`?${string}` | `#${string}` | ''}` | `/projects/CalendarTabSimplified${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projects/PartTab${`?${string}` | `#${string}` | ''}` | `/projects/PartTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projects/VenueTab${`?${string}` | `#${string}` | ''}` | `/projects/VenueTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projects${`?${string}` | `#${string}` | ''}` | `/projects${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects/CalendarTabSimplified` | `/projects/CalendarTabSimplified`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects/PartTab` | `/projects/PartTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects/VenueTab` | `/projects/VenueTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/projects/${Router.SingleRoutePart<T>}` | `/projects/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/projects/venue/${Router.SingleRoutePart<T>}` | `/projects/venue/${Router.SingleRoutePart<T>}` | { pathname: `${'/(tabs)'}/projects/[id]` | `/projects/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/projects/venue/[id]` | `/projects/venue/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
